logs:
  - name: root
    level: INFO
    appenders: 
      - type: FileLogAppender
        file: /home/zhuyh/Code/GraduationDesign/zhuyh/logs/LogRoot.txt
      - type: StdoutAppender
  - name: system
    level: INFO
    appenders: 
      - type: FileLogAppender
        file: /home/zhuyh/Code/GraduationDesign/zhuyh/logs/LogSystem.txt
      - type: StdoutAppender
